name: print env variable

on:
  push:
    branches:
      - Day02

  workflow_dispatch:

env:
  APP_NAME: myapp
  ENV: production-ready

jobs:
  print-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Print environment variables
        run: |
          echo "App Name: $APP_NAME"
          echo "Environment: $ENV"