name: secrets practice

on:
  push:
    branches:
      - Day03

  workflow_dispatch:

jobs:
  secrets-job:
    runs-on: ubuntu-latest

    steps:
      - name: access secrets
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}

        run: echo "The username is $USERNAME"